### ISSUE TITLE
"Cannot read property '_cursorDescription' of undefined" in metrics/reportObserversMetrics.js:27:41

### ISSUE THREAD

**Issue by SimonSimCity** [kschingiz/meteor-measured#2]
I just ran into the following error on my console using this package in version `1.0.3`:

```
Uncaught Exception: TypeError: Cannot read property '_cursorDescription' of undefined
    at Object.values.forEach.handle (packages/kschingiz:meteor-measured/metrics/reportObserversMetrics.js:27:41)
    at Array.forEach (<anonymous>)
    at Object.values.forEach.muxer (packages/kschingiz:meteor-measured/metrics/reportObserversMetrics.js:23:28)
    at Array.forEach (<anonymous>)
    at reportObservers (packages/kschingiz:meteor-measured/metrics/reportObserversMetrics.js:20:31)
    at Gauge.registry.getOrCreateGauge [as _readFn] (packages/kschingiz:meteor-measured/metrics/meteor.js:26:11)
    at Gauge.toJSON (/bundle/programs/server/npm/node_modules/meteor/kschingiz_meteor-elastic-apm/node_modules/measured-core/lib/metrics/Gauge.js:24:17)
    at metrics.forEach.metric (/bundle/programs/server/npm/node_modules/meteor/kschingiz_meteor-elastic-apm/node_modules/elastic-apm-node/lib/metrics/reporter.js:39:36)
    at Array.forEach (<anonymous>)
    at afterAll (/bundle/programs/server/npm/node_modules/meteor/kschingiz_meteor-elastic-apm/node_modules/elastic-apm-node/lib/metrics/reporter.js:30:15)
    at /bundle/programs/server/npm/node_modules/meteor/kschingiz_meteor-elastic-apm/node_modules/after-all-results/index.js:20:25
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
```

I've just quickly reported it here - I'll check it out later if someone else doesn't resolve it first.

**Comment by arty-ms** [comment]
Hey @SimonSimCity , did you find the cause of this problem?

**Comment by SimonSimCity** [comment]
@arty-ms Don't remember ... but I'm not so much involved in meteor projects anymore...
